<a href="https://colab.research.google.com/github/Yashasvi-30/Predictive-Analysis/blob/main/Numpy-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1D, 2D, and 3D array creation
print("Array Creation:")
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array:", array_1d)
print("2D Array:\n", array_2d)
print("3D Array:\n", array_3d)

# Creating arrays using np.arange, np.linspace
array_arange = np.arange(0, 10, 2)
array_linspace = np.linspace(0, 1, 5)

print("Array with np.arange:", array_arange)
print("Array with np.linspace:", array_linspace)

# Basic operations: Indexing, Slicing, Reshaping
print("\nArray Indexing and Slicing:")
print("First element of array_1d:", array_1d[0])
print("Slice of array_2d (first row):", array_2d[0, :])
print("Reshaped array_arange (2x2):\n", array_arange[:4].reshape(2, 2))

# Concatenation
print("\nArray Concatenation:")
concat_array = np.concatenate([array_1d, np.array([6, 7, 8])])
print("Concatenated Array:", concat_array)

# Investigate attributes
print("\nArray Attributes:")
print("Shape of array_2d:", array_2d.shape)
print("Size of array_2d:", array_2d.size)
print("Data type of array_2d:", array_2d.dtype)
print("Number of dimensions of array_3d:", array_3d.ndim)

# Methods: reshape, resize, flatten
print("\nReshape, Resize, and Flatten:")
reshaped_array = array_1d.reshape(1, 5)
resized_array = np.resize(array_1d, (3, 3))  # Note: This modifies the structure
flattened_array = array_2d.flatten()

print("Reshaped Array:\n", reshaped_array)
print("Resized Array:\n", resized_array)
print("Flattened Array:", flattened_array)



Array Creation:
1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Array with np.arange: [0 2 4 6 8]
Array with np.linspace: [0.   0.25 0.5  0.75 1.  ]

Array Indexing and Slicing:
First element of array_1d: 1
Slice of array_2d (first row): [1 2 3]
Reshaped array_arange (2x2):
 [[0 2]
 [4 6]]

Array Concatenation:
Concatenated Array: [1 2 3 4 5 6 7 8]

Array Attributes:
Shape of array_2d: (2, 3)
Size of array_2d: 6
Data type of array_2d: int64
Number of dimensions of array_3d: 3

Reshape, Resize, and Flatten:
Reshaped Array:
 [[1 2 3 4 5]]
Resized Array:
 [[1 2 3]
 [4 5 1]
 [2 3 4]]
Flattened Array: [1 2 3 4 5 6]


In [2]:
import numpy as np

# Load dataset using NumPy
# Replace 'your_dataset.csv' with the path to a real CSV file
try:
    data = np.genfromtxt('mutual_funds_DS.csv', delimiter=',', skip_header=1)
    print("\nLoaded Data:\n", data)
except FileNotFoundError:
    print("\nDataset not found! Replace 'your_dataset.csv' with an actual file.")

# Cleaning and Preprocessing
# Simulating a dataset for demonstration
data = np.array([[1, 2, np.nan], [4, 5, 6], [7, np.nan, 9]])

print("\nOriginal Data:\n", data)

# Handle missing values
data[np.isnan(data)] = np.mean(data[~np.isnan(data)])
print("\nData after Handling Missing Values:\n", data)

# Normalization (min-max scaling)
data_minmax = (data - data.min()) / (data.max() - data.min())
print("\nData after Normalization (Min-Max Scaling):\n", data_minmax)

# Standardization (Z-score normalization)
data_standardized = (data - data.mean(axis=0)) / data.std(axis=0)
print("\nData after Standardization (Z-Score Normalization):\n", data_standardized)

# Statistical Measures
print("\nStatistical Measures:")
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))
print("Sum:", np.sum(data))
print("Max:", np.max(data))
print("Min:", np.min(data))



Loaded Data:
 [[   nan  100.   100.  ...    4.     6.5    6.9]
 [   nan 1000.  1000.  ...    5.6    4.8    5.5]
 [   nan 1000.  1000.  ...    2.    18.9    9.7]
 ...
 [   nan  500.   500.  ...    5.3    3.8    nan]
 [   nan  500.   500.  ...    1.7   32.4   13.3]
 [   nan  500.   500.  ...    5.3    4.5    nan]]

Original Data:
 [[ 1.  2. nan]
 [ 4.  5.  6.]
 [ 7. nan  9.]]

Data after Handling Missing Values:
 [[1.         2.         4.85714286]
 [4.         5.         6.        ]
 [7.         4.85714286 9.        ]]

Data after Normalization (Min-Max Scaling):
 [[0.         0.125      0.48214286]
 [0.375      0.5        0.625     ]
 [0.75       0.48214286 1.        ]]

Data after Standardization (Z-Score Normalization):
 [[-1.22474487 -1.41295331 -1.00850764]
 [ 0.          0.75817007 -0.35434052]
 [ 1.22474487  0.65478324  1.36284817]]

Statistical Measures:
Mean: 4.857142857142858
Median: 4.857142857142857
Standard Deviation: 2.281742581087798
Variance: 5.2063492063492065
Sum: 43.